
name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: install dependencies
        run:
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
          pip install -r api_yamdb/requirements.txt

      - name: test against flake8 and pytest
        run: |
          python -m flake8
          pytest


